%CompareHist test

warning('off','images:dicominfo:fileVRDoesNotMatchDictionary');

[filename1, pathname1, ~] = uigetfile( ...
       {'*.*',  'All Files (*.*)'}, ...
        'Pick a file', ...
        'MultiSelect', 'off');
[filename2, pathname2, ~] = uigetfile( ...
       {'*.*',  'All Files (*.*)'}, ...
        'Pick a file', ...
        'MultiSelect', 'off');
I1=dicominfo(strcat(pathname1,filename1));
I2=dicominfo(strcat(pathname2,filename2));
im1 = dicomread(I1);
im2 = dicomread(I2);
%c = compareHist(im1,im2,max(max(max(im1)),max(max(im2))),0.8);
c = compareHist(im1,im2,I1.BitDepth,I2.BitDepth,0.8);
